### ISSUE TITLE
Manual processing should use popups

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.banking#142]
The manual processing often makes you create new contributions. This workflow would be significantly improved when we would make use of CiviCRM 4.5+'s popups.

**Comment by VangelisP** [comment]
Looks like if you disable popups in 4.6.x, nothing appears, not even in a new window, therefore you lose the data entry.

**Comment by VangelisP** [comment]
And since my clients are old-fashioned but still wanted to have 4.6, here's a fix for master release which respects the option 'Enable Popup Forms' on Display Settings.
Comes in a form of patch, but very easy to add.
No side-effects so far and now I can see my pages opening in a new window in case transaction needs manual data entry.
[popup_enhanced.patch.zip](https://github.com/Project60/org.project60.banking/files/270976/popup_enhanced.patch.zip)

By hand, on **CRM/Banking/Page/Review.php** , on line 249:
`      if ($popups_allowed) {`
`$enabled_popups = CRM_Core_BAO_Setting::getItem('CiviCRM Preferences','ajaxPopupsEnabled');`
`        if (!$enabled_popups) {`
`          $popups_allowed = 0;`
`        }`
`      }`

**Comment by systopia** [comment]
Thanks @VangelisP, that makes perfect sense. I'll add it soon.

**Comment by systopia** [comment]
I added your fix in https://github.com/Project60/org.project60.banking/tree/dev_142.

@VangelisP: Could you please check if that works for you?

**Comment by VangelisP** [comment]
@systopia yes, I've just rolled it on our production replica and it's working properly. 
If you've checked the 'show popups' , contribution data opens in a popup.
If you haven't checked the 'show popups', contribution data opens in a new window.

**Comment by systopia** [comment]
@VangelisP: Thanks, I merged it into ``master``
