### ISSUE TITLE
Faster/smarter contact lookup

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.banking#214]
I'm dealing with civibanking on a fairly large base (>1.5M contacts) and the default matcher is both too slow  (more than 30 seconds for a lookup) and match with too many contacts (we have contacts with only first names and they match as much as the better first name + last name) 

summary BankingLookup:
eg with a name in the transaction "dutoit, xavier" (in our case, about half of the names are last,first, the other is "first last")

it will split the name, so "xavier" "dutoit" and keep only the longest 4 (so irrelevant in our example)

for the simple "first + last", it generates all the combination
    [0] => dutoit, xavier
    [1] => dutoit
    [2] => dutoit, xavier
    [3] => xavier, dutoit
    [4] => xavier

improvement one: remove duplicate entries
improvement 2: try to find if one or several contacts have their sort_name that is one of the longest combination ("dutoit, xavier" or "xavier, dutoit") and if it's the case, skip the advanced changes

otherwise, if will lookup (getquick api or sql) all the combinations as before

**Comment by systopia** [comment]
It's a good idea, but I couldn't pull it in your version, because it would change the behaviour quite radically in case there's a direct match. I can see that this is what you want, but not necessarily what other people need.

Therefore I changed it; your behaviour should now happen if you pass ``exact_match_wins=1``.

@tttp Does that work for you?
